<a href="https://colab.research.google.com/github/manuel761/StatsQuest/blob/main/StatQuest3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install lightning

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam

import lightning as L
from torch.utils.data import TensorDataset,DataLoader


import pandas as pd


from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('/content/iris.data')

In [ ]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
df.columns = ["sepal_length",
              "sepal_width",
              "petal_length",
              "petal_width",
              "class"]

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
df.shape

(149, 5)

In [ ]:
df['class'].nunique()

3

In [ ]:
for class_name in df['class'].unique():
  print(class_name, ": " , sum(df['class']==class_name),sep='')

Iris-setosa: 49
Iris-versicolor: 50
Iris-virginica: 50

In [ ]:
df[['petal_width', 'sepal_width']].head()

   petal_width  sepal_width
0          0.2          3.0
1          0.2          3.2
2          0.2          3.1
3          0.2          3.6
4          0.4          3.9

In [ ]:
input_values=df[['petal_width', 'sepal_width']]
input_values.head()

   petal_width  sepal_width
0          0.2          3.0
1          0.2          3.2
2          0.2          3.1
3          0.2          3.6
4          0.4          3.9

In [ ]:
label_values=df['class']
label_values.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [ ]:
# Convert the strings in the 'class' column into numbers with factorize()
classes_as_numbers = label_values.factorize()[0]
classes_as_numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
input_train, input_test, label_train, label_test = train_test_split(input_values,
                                                                    classes_as_numbers,
                                                                    test_size=0.25,
                                                                    stratify=classes_as_numbers,
                                                                    random_state=42)

In [ ]:
input_train

     petal_width  sepal_width
129          1.9          2.8
121          2.0          2.8
98           1.3          2.8
53           1.5          2.8
85           1.5          3.1
..           ...          ...
34           0.2          3.2
37           0.2          3.0
5            0.3          3.4
88           1.3          2.5
3            0.2          3.6

[111 rows x 2 columns]

In [ ]:
label_train

array([2, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1,
       0, 1, 2, 0, 2, 1, 2, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 2, 2,
       0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 2, 2, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1,
       0, 2, 1, 2, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0, 2,
       2, 2, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1,
       0])

In [ ]:
input_test.shape

(38, 2)

In [ ]:
label_test.shape

(38,)

In [ ]:

one_hot_label_train = F.one_hot(torch.tensor(label_train)).type(torch.float32)

In [ ]:
one_hot_label_train[:10]

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [ ]:
one_hot_label_train[:10]

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [ ]:
max_vals_in_input_train = input_train.max()
max_vals_in_input_train

petal_width    2.5
sepal_width    4.2
dtype: float64

In [ ]:
min_vals_in_input_train = input_train.min()

min_vals_in_input_train

petal_width    0.1
sepal_width    2.0
dtype: float64

In [ ]:
input_train = (input_train - min_vals_in_input_train) / (max_vals_in_input_train - min_vals_in_input_train)
input_train.head()

     petal_width  sepal_width
129     0.750000     0.363636
121     0.791667     0.363636
98      0.500000     0.363636
53      0.583333     0.363636
85      0.583333     0.500000

In [ ]:
input_test = (input_test - min_vals_in_input_train) / (max_vals_in_input_train - min_vals_in_input_train)
input_test.head()

    petal_width  sepal_width
14     0.125000     1.090909
76     0.666667     0.454545
52     0.500000     0.136364
84     0.625000     0.636364
20     0.125000     0.772727

In [ ]:
input_train_tensors = torch.tensor(input_train.values).type(torch.float32)
input_train_tensors[:10]

tensor([[0.7500, 0.3636],
        [0.7917, 0.3636],
        [0.5000, 0.3636],
        [0.5833, 0.3636],
        [0.5833, 0.5000],
        [1.0000, 0.5909],
        [0.0000, 0.5000],
        [0.7083, 0.3182],
        [0.0417, 0.6364],
        [0.7083, 0.3636]])

In [ ]:
input_test_tensors = torch.tensor(input_test.values).type(torch.float32)

input_test_tensors[:10]

tensor([[0.1250, 1.0909],
        [0.6667, 0.4545],
        [0.5000, 0.1364],
        [0.6250, 0.6364],
        [0.1250, 0.7727],
        [0.5833, 0.4545],
        [0.5417, 0.2727],
        [0.9167, 0.5000],
        [0.7083, 0.4091],
        [0.8750, 0.3636]])

Now that we have tensors for input_train, named input_train_tensors, and we have the one-hot encoded class values stored in tensors called label_train, we can combine them into a TensorDataset that are, in turn, turned into DataLoader.

In [ ]:
train_dataset = TensorDataset(input_train_tensors, one_hot_label_train)
train_dataloader = DataLoader(train_dataset)

# Neural Network

In [ ]:

class MultipleInOuts(L.LightningModule):

    def __init__(self):
        super().__init__()

        # set seed
        L.seed_everything(seed=42)

        # layers
        self.input_to_hidden = nn.Linear(
            in_features=2,
            out_features=2,
            bias=True
        )

        self.hidden_to_output = nn.Linear(
            in_features=2,
            out_features=3,
            bias=True
        )

        # loss function
        self.loss = nn.MSELoss(reduction='sum')

    def forward(self, inputs):

        hidden = self.input_to_hidden(inputs)

        output_values = self.hidden_to_output(
            torch.relu(hidden)
        )

        return output_values

    def configure_optimizers(self):

        return Adam(
            self.parameters(),
            lr=0.001
        )

    def training_step(self, batch, batch_idx):

        inputs, labels = batch

        outputs = self.forward(inputs)

        loss = self.loss(outputs, labels)

        return loss

In [ ]:
model=MultipleInOuts()

INFO: Seed set to 42
INFO:lightning.fabric.utilities.seed:Seed set to 42

In [ ]:
for name,params in model.named_parameters():
  print(name,torch.round(params.data,decimals=2))

input_to_hidden.weight tensor([[ 0.5400,  0.5900],
        [-0.1700,  0.6500]])
input_to_hidden.bias tensor([-0.1500,  0.1400])
hidden_to_output.weight tensor([[-0.3400,  0.4200],
        [ 0.6200, -0.5200],
        [ 0.6100,  0.1300]])
hidden_to_output.bias tensor([0.5200, 0.1000, 0.3400])


Training our Neural Network

In [ ]:
model = MultipleInOuts()

INFO: Seed set to 42
INFO:lightning.fabric.utilities.seed:Seed set to 42

In [ ]:
trainer = L.Trainer(max_epochs=10)
trainer.fit(model, train_dataloaders=train_dataloader)

INFO: GPU available: False, used: False
INFO:lightning.pytorch.utilities.rank_zero:GPU available: False, used: False
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type    ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ input_to_hidden  │ Linear  │      6 │ train │     0 │
│ 1 │ hidden_to_output │ Linear  │      9 │ train │     0 │
│ 2 │ loss             │ MSELoss │      0 │ train │     0 │
└───┴──────────────────┴─────────┴────────┴───────┴───────┘

Trainable params: 15
Non-trainable params: 0
Total params: 15
Total estimated model params size (MB): 0
Modules in train mode: 3
Modules in eval mode: 0
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
INFO: `Trainer.fit` stopped: `max_epochs=10` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=10` reached.

In [ ]:
predictions=model(input_test_tensors)

In [ ]:
predictions[0:4,]

tensor([[ 0.8385, -0.0219,  0.1416],
        [ 0.1137,  0.4395,  0.5244],
        [ 0.1874,  0.3835,  0.3733],
        [ 0.2120,  0.3794,  0.5023]], grad_fn=<SliceBackward0>)

In [ ]:
predicted_labels=torch.argmax(predictions,dim=1) # dim=0 applies argmax to rows, dim=1 applies argmax to columns
predicted_labels[0:4]

tensor([0, 2, 1, 2])

In [ ]:
torch.sum(torch.eq(torch.tensor(label_test), predicted_labels)) / len(predicted_labels)

tensor(0.7368)

And we see that our neural network only correctly predicts 74% of the testing data. This isn't very good. So, will training our model for more epochs improve the model's predictions?

One way to answer that question is to just train for longer and see what happens.

The good news is that because we're using Lightning, we can pick up where we left off training without starting over from scratch. This is because training with Lightning creates checkpoint files that keep track of the Weights and Biases as they change. As a result, all we have to do to pick up where we left off is tell the Trainer where the checkpoint files are. This is awesome and will save us a lot of time since we don't have to retrain the first 10 epochs. So, let's add an additional 90 epochs to the training.

To add additional epochs to the training, we first identify where the checkpoint file is with the following command.

In [ ]:
path_to_checkpoint = trainer.checkpoint_callback.best_model_path ## By default, "best" = "most recent"

Then we create a new Lightning Trainer, just like before, but we set the number of epochs to 100. Given that we already trained for 10 epochs, this means we'll do 90 more.

In [ ]:
## First, create a new Lightning Trainer
trainer = L.Trainer(max_epochs=100) # Before, max_epochs=10, so, by setting it to 100, we're adding 90 more.

INFO: GPU available: False, used: False
INFO:lightning.pytorch.utilities.rank_zero:GPU available: False, used: False
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

In [ ]:
## Then call trainer.fit() using the path to the most recent checkpoint files
## so that we can pick up where we left off.
trainer.fit(model, train_dataloaders=train_dataloader, ckpt_path=path_to_checkpoint)

INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: Restoring states from the checkpoint path at /content/lightning_logs/version_0/checkpoints/epoch=9-step=1110.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restoring states from the checkpoint path at /content/lightning_logs/version_0/checkpoints/epoch=9-step=1110.ckpt
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py:566: The dirpath has changed from '/content/lightning_logs/version_0/checkpoints' to '/content/lightning_logs/version_1/checkpoints', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type    ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ input_to_hidden  │ Linear  │      6 │ train │     0 │
│ 1 │ hidden_to_output │ Linear  │      9 │ train │     0 │
│ 2 │ loss             │ MSELoss │      0 │ train │     0 │
└───┴──────────────────┴─────────┴────────┴───────┴───────┘

Trainable params: 15
Non-trainable params: 0
Total params: 15
Total estimated model params size (MB): 0
Modules in train mode: 3
Modules in eval mode: 0
Total FLOPs: 0

INFO: Restored all states from the checkpoint at /content/lightning_logs/version_0/checkpoints/epoch=9-step=1110.ckpt
INFO:lightning.pytorch.utilities.rank_zero:Restored all states from the checkpoint at /content/lightning_logs/version_0/checkpoints/epoch=9-step=1110.ckpt

Output()

INFO: `Trainer.fit` stopped: `max_epochs=100` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=100` reached.

In [ ]:
predictions = model(input_test_tensors)

In [ ]:
predicted_labels = torch.argmax(predictions, dim=1)

In [ ]:
torch.sum(torch.eq(torch.tensor(label_test), predicted_labels)) / len(predicted_labels)

tensor(0.8947)

# Make a Prediction with New Data

Now that our model is trained, we can use it to make predictions from new data. This is done by passing the model a tensor with normalized petal and sepal widths wrapped up in a tensor.

For example, if the raw petal and sepal width measurements were 0.2 and 3.0, we would first normalize them using the maximum and minimum values we calculated with the training data.

In [ ]:
normalized_values = ([0.2, 3.0] - min_vals_in_input_train) / (max_vals_in_input_train - min_vals_in_input_train)
normalized_values

petal_width    0.041667
sepal_width    0.454545
dtype: float64

Then we convert normalized_values into a tensor and pass it to the model to see what it predicts.

In [ ]:
model(torch.tensor(normalized_values).type(torch.float32))

/tmp/ipykernel_5232/3219751161.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model(torch.tensor(normalized_values).type(torch.float32))

tensor([ 0.7489,  0.2515, -0.0650], grad_fn=<ViewBackward0>)

And first output has the largest value, meaning that the neural network predicts that the measurements come from Setosa.